language: python
dist: xenial
addons:
  apt:
    packages:
      - python3
      - "python3-pip"
      - docker-ce
python:
  - "3.6"
install:
  - "pip install --upgrade pip wheel setuptools"
  - "pip install -r requirements.txt"

script: pytest --durations=10